#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-xgboost
Version  : 2.0.0
Release  : 10
URL      : https://files.pythonhosted.org/packages/bc/f5/31bf11e175c18cde6cc71c5d3447c140f2c08861ce7b5b8b76ea1dbc7322/xgboost-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/bc/f5/31bf11e175c18cde6cc71c5d3447c140f2c08861ce7b5b8b76ea1dbc7322/xgboost-2.0.0.tar.gz
Summary  : XGBoost Python Package
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: pypi-xgboost-license = %{version}-%{release}
Requires: pypi-xgboost-python = %{version}-%{release}
Requires: pypi-xgboost-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : pypi(hatchling)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This document is generated by sphinx.
Make sure you cloned the following repos in the root.

%package license
Summary: license components for the pypi-xgboost package.
Group: Default

%description license
license components for the pypi-xgboost package.


%package python
Summary: python components for the pypi-xgboost package.
Group: Default
Requires: pypi-xgboost-python3 = %{version}-%{release}

%description python
python components for the pypi-xgboost package.


%package python3
Summary: python3 components for the pypi-xgboost package.
Group: Default
Requires: python3-core
Provides: pypi(xgboost)
Requires: pypi(numpy)
Requires: pypi(scipy)

%description python3
python3 components for the pypi-xgboost package.


%prep
%setup -q -n xgboost-2.0.0
cd %{_builddir}/xgboost-2.0.0
pushd ..
cp -a xgboost-2.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694533717
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-xgboost
cp %{_builddir}/xgboost-%{version}/cpp_src/LICENSE %{buildroot}/usr/share/package-licenses/pypi-xgboost/4d98c20884442064704475a2c7092515382cfe48 || :
cp %{_builddir}/xgboost-%{version}/cpp_src/dmlc-core/LICENSE %{buildroot}/usr/share/package-licenses/pypi-xgboost/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/xgboost-%{version}/cpp_src/rabit/LICENSE %{buildroot}/usr/share/package-licenses/pypi-xgboost/6f755c9a3e0bbbfda2f9a37a7102e0606ea145f5 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-xgboost/4d98c20884442064704475a2c7092515382cfe48
/usr/share/package-licenses/pypi-xgboost/6f755c9a3e0bbbfda2f9a37a7102e0606ea145f5
/usr/share/package-licenses/pypi-xgboost/92170cdc034b2ff819323ff670d3b7266c8bffcd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
